import "server-only";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SupabaseAuthProvider from "@/components/provider/SupabaseAuthProvider";
import SupabaseProvider from "@/components/provider/SupabaseProvider";
import { createClient } from "@/lib/utils/supabase-server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();
  return (
    <html lang="en">
      <SupabaseProvider>
        <SupabaseAuthProvider serverSession={session}>
          <body className={inter.className}>
            <main className="min-h-screen bg-background flex flex-col items-center">
              {children}
            </main>
          </body>
        </SupabaseAuthProvider>
      </SupabaseProvider>
    </html>
  );
}
